/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mgh.edd.examengradle;

public class App {
    public String getGreeting() {
        return "Ventajas de utilizar git: Git al ser un Controlador de versiones distribuido, permite un desarrollo flexible, también facilita el trabajo en equipo, nos da un registro completo de las modificaciones que se hacen en el código y además permite el seguimiento y la asiganción de tareas."; 

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
